default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: test_ci_dev
  username: postgres
  host: localhost
  password: postgres

test:
  <<: *default
  database: test_ci_test
  username: postgres
  password: postgres
  host: localhost

production:
  <<: *default
  adapter: postgresql
  encoding: unicode
  database: test_ci_prod
  username: postgres
  password: postgres
  host: localhost
  port: 5432
